//
// Created by antoine on 26/09/2019.
//

#include "picotls/protoop.h"

proto_op_id_t PROTOOP_NO_PARAM_AEAD_DECRYPT = {.id = PROTOOPID_NOPARAM_AEAD_DECRYPT};
proto_op_id_t PROTOOP_NO_PARAM_HANDLE_INPUT = {.id = PROTOOPID_NO_PARAM_HANDLE_INPUT};
proto_op_id_t PROTOOP_NO_PARAM_BUFFER_PUSH_ENCRYPTED_RECORDS = {.id = PROTOOPID_NO_PARAM_BUFFER_PUSH_ENCRYPTED_RECORDS};